### ISSUE TITLE
Running OPT-175B on CPU or 16 40GB A100s

### ISSUE THREAD

**Issue by ANarayan** [facebookresearch/metaseq#58]
Request: Documentation for running OPT-175B on a CPU or smaller GPU-based machines (16 NVIDIA A100 40GB Machines)

I am interested in running the text generation interface with the OPT-175B parameter model. However, I only have access to 16 40GB A100 machines. Is it possible to run inference on the model given these compute resources? Any guidance would be greatly appreciated!

**Comment by stephenroller** [comment]
We'll need to release the FSDP sharded version to do this.

**Comment by ANarayan** [comment]
awesome! thank you!!!

**Comment by stephenroller** [comment]
Since it seems like we did release the FSDP shards, the sketch of the solution is this:

1. Grab the 992 FSDP shards
2. Run `consolidate_fsdp` to reduce this to MP 8, DP size 2 (total shards 16)
3. Launch via slurm with MODEL_PARALLEL set to 8 and WORLD_SIZE set to 16.

CPU would be incredibly expensive. :(

**Comment by ekinakyurek** [comment]
Hi @stephenroller,

Thanks for the solution but I think I didn't fully get it. How DP can reduce the memory requirement of the model itself? Even, then, how can we provide MP=8, DP=2 arguments to the consolidate scripts. it seems that it doesn't take such arguments, and by default it reduces the models into a single shard? Apologies if I misunderstand.

https://github.com/facebookresearch/metaseq/blob/1246d720284305e5031ff6db16870cd140c2a9a5/metaseq/distributed/stitch_fsdp_ckpt.py#L32-L37

**Comment by stephenroller** [comment]
See #131 for most recent guidance.

CPU is out of the question right now. (I mean, if you want to do it, just comment out all the calls to .cuda() and suffer the consequences. Probably many minutes per token generated)

**Comment by stephenroller** [comment]
Moving everything to #131 as the main location of progress.

**Comment by zfchenUnique** [comment]
> #131



> Hi! Any updates on this?
> 
> We are on a similar situation, with access to 40GB A100 nodes and researchers interested in running the 175B model, but the `consolidate_fsdp.py` script did not finish properly (this was on a ~800G machine).
> 
> ```
> (opt175b) [acb11899xv@m01 metaseq]$ python  metaseq/scripts/consolidate_fsdp_shards.py /groups/gcb50389/datasets/OPT175B/shards/ ./fsdp/
> 100%|█████████████████████████████████████████████████████████████████████████████████| 992/992 [32:32<00:00,  1.97s/it]
> Killed
> ```
> 
> Any hints would be much appreciated.

I have a similar issue on a machine with similar memory (~800G). It is killed too. Has anyone had any idea what is wrong?

**Comment by asolano** [comment]
Hi, Zhenfang.

This issue seems to be closed but just in case we solved it by using a swap file, it's slow but it works:

https://github.com/alpa-projects/alpa/issues/702

As for the reason, even if the machine has enough RAM the system may be configured to limit the per process maximum, or some other processes may be running at the same time reducing the free memory available for the script.

Best,

Alfredo
